steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build','.','-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/todo-demo2/$COMMIT_SHA']
images:
- 'us-east1-docker.pkg.dev/$PROJECT_ID/todo-demo2/$COMMIT_SHA'