steps:
- name: 'docker.io/library/python:3.7'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install -r requirements.txt && pytest .'
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: [ 'build','.','-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/todo-demo2/$COMMIT_SHA']
images:
- 'us-east1-docker.pkg.dev/$PROJECT_ID/todo-demo2/$COMMIT_SHA'